language: ruby
rvm:
  - ruby-head
  - 2.7
  - 2.6
  - 2.5
  - 2.4
matrix:
  allow_failures:
    - rvm: ruby-head
bundler_args: "--without development"
script:
- bundle exec rspec
env:
  global:
  - secure: vbERxVcsYQcYDD8h7d+hobOUXxnztPJLHRRy/1Rh94jDL76/pS56VXtWPBmZbJ+oS0TDvHJ91wkKu9sQlDa2MdTDUA35CA78L/9JWzrmtSrOypUfxJkOyM43VDgZvKu0ioMTgzyb4nJ1opTOYX4P7+x6pGLu2ox3YgR0kHb3qB1BdV3PFlk8E0X2IZ62qE/VGYICBVBrDmxmp4BVowd0i+XmWjkqNexvsO/lJGaG7BQBjBh20TaNlCWhB50BlgEoAjImN0rKdfkoNd0A6+Pek98VLrfjkxuA0slZ5KVWdlSd2yNU8JBWCB4miHQtNbVU428Wee9N64bQdrtVapa5ZYsCjTd8SgwlxEzVuXAIqtCorgfvfNELwX/gmFb3KZma9S0MnxxBhU9TB1MHxCRVBVyLz9+/B5zvBynyYnnDduhRav/8ZrWPfWXOFmiyK1Nt7YMEMVhSadIiRoYpYote0IE+6Ludk6VmYWPCPqK4Akm3e4FybkFZD2cy0P3Yn7WJPsbWOGGwD4iCEKJV2uZ4Nd4s8bHihWmclJlhgv9P4eYl0+eZSO5qSOGLbYAM9JWRKHihyDvLN3zT6qDraLV+fx/B6JErvc2WUBMYgHioR/E2PrrgbwHX2aVZiBKHjZKVjkdP6hjRGHEE0rGVFsEy7sF3mQkuWXHFHStJhB9FUTg=
  - secure: wArQba5douPo58nI7BTEBRTyJNt/ovWXzdaxh2LShj7+c8K87wmc8JZxy7zs3Z27iGrChak8eP+Ooa/3fHZkuhmmbQijXF0aOkv1tTGrBZYN5pgzh+ggNE9XEx1n3KmbyjFdxuxT1mQzUD9Anhzo3LAapAKZGm3tOme+4BZrdwx+VtuORgxW0UdXUMUV3u4e0oFxj3nfyZ/bWCw0HapOopZrDjdmK26rx1+mXrCBYInMMCMtP+mSRIIdm/7tzaTnwubcWbZ0gk3XficNib0E2rol7abuH+ThMXZDinwFStJFt/3UVnGpnmiALlHILda2bIhh3Kofv8RKn8coHY3eBao4l8lQo2ct4PuK9ydCHQBcYgZxlcWI6K+ogCBQo1Yhs5HhlPXbeMVkfbrMcYJZeZAnnJsqRh+hroUGxItI9fDDcDcvd0gZbmWecCU/3u44tDMVp2jaMV3i4jN/Ywa85LcMtgj1v0UlHi8CFU1MdUCyfwCvcpauA1D5arrSVKTmJS75ftF1xngUtUf7lN62nGK5NN0sQG0k6mIMoHBRwPCwjue7/bJNwDRDLwIOgKt7brwhGndu6UtujQ7YYW3ZwPYTGYb8adg4HzroZmpEq6EPeP9L8B/AvpA+sNjkie/Ep/MQqF2nTj8e0ZFjDJKhyWS+ceFvv70iwR8xZHIV/5A=
