language: ruby
rvm:
- ruby-head
- 2.3.0
- 2.2
- 2.1
bundler_args: "--without development"
script:
- bundle exec rspec
env:
  global:
  - secure: ENByEPiVW58zbkBXDQJS0UJm0t4WE9xlDzziJYGLXTinT5zQS1keTBXgjeEJ5yQZ36FquaWllwdQoQO3DqsyjoeMKFW8F47+ftkjWSuCgUJvtmqCc7/Si+yJVnvh4ZzO7Qx4kTbYu5H2WbkynAXFuLGux8DF71qshKpri22AmP/uavi2g5e2a0zWT1ORxN3kx0wTiSR0AdrXsqPGAbM6DgqKU5zGJyCqoat7ARcUjidLoupzf46Ur6IkxX5fMlvcqcNQKq0llWkBMi29TixTCKKd4IyiQvL9vz4ziWyBylUPseIpLIiqXCTegylxTA+fbgMx41MTvL+7UupfaYpxTq507tI4LNOZFEE2MrkVTlHSZiQJrE9hyyoGY/fhqhVtjMIhru6XaiRODuaa9MpaGEnOx+cgjMpMOuYGOdEEUkSY3HcL6kYrJIFKxp900mKaOCda2GVPCfmSbqR5kXVFo4Bw9Hq2xbv+x5VTdK0EleTHJH7+uV1uSaPOzfmaSOF/zJv7hTrAkek8rPawQ6WHDEjE1WfbkfSk1VT4GvPJ8+hQmxjBD5ihigK65dAlSZUo4wdWy2dAwr07UqHfkgh+32NxkccKaAj61SLc+pVGhuGtieBl62DAycO0E2uqjAotUKMgSTTXzU9MUuncu5f3kfxg1x86/tkGk0G2IY/JuJo=
  - secure: DerTLH+5WIYs10Ww3k/qLAQ89Bqqufu73JwROpqjLr7a7V7xX5X61FSRM62ISF7Kfqu91aVqm79zoZqFlhE7BmUSRW6OTs2nZX/c84C7O3ptjngxiuTEXKlcFf1EOiQj2RWzgYnbjkhwM4N7q6Xk97XXqhuWGX9hnB8R1ESu0PcUhcQJrvWvQeSuDGYtMWoay8m3fDBzN/M4Tu/3WLDHpLSRjpP4ofGtooZRk5XsDA/F04XZm22pT+h3JBAMPT7CixiUnC0WVLUXowpNIlDM00DeoxIVK2yE8vlN/U7e1iQE85pK52gQ/N8QgiTnPddQeDy9UWjLwSzBoYHdJ+pS14OalUd/ESFM9YDP1NjWss2gJtZeuMMfyCrKvf5ASm+DVqbbhZ8zfH0ulwnlK0aFIgas685eBcY3Y1LhunBQE+f+ZC/gpAZRhwAt4DIz4hExjvOWCpCM+5C4fRtqmkfmg3hLJRG6UQ+oC2IpQ9W1NFAHz4guUFN7fEUEA+CZj0mv8aNEL4rZ/GSnU1sDQu/1rmVh9Ra8i0hIFKn6/FIgGFpQt2NXa7Qryqakl8UTIE+/H9hCnXqYZCIguXVo8TpvGTzjGpAaLTCaGatd/9l6w1OtUv0RzC9i2JJbWy5MXZc+stCTYip0iso751BjnJfLSsPC5LMfRF2zFP97w7HoF8Y=
