name: docker-hub-push
on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
jobs:
  docker-hub-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set tag environment variable
        run: |
          echo "git_describe_version=$(git describe)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            onlyoffice/telegram-github-changes-bot:latest
            onlyoffice/telegram-github-changes-bot:${{ env.git_describe_version }}
