name: CI
on: [push]
jobs:
  ruby:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-failures }}
    strategy:
      matrix:
        ruby: ['3.4']
        allow-failures: [false]
        include:
          - ruby: head
            allow-failures: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Init default config
        env:
          CHANGES_BOT_GH_TOKEN: ${{ secrets.CHANGES_BOT_GH_TOKEN }}
          CHANGES_BOT_GH_API: ${{ secrets.CHANGES_BOT_GH_API }}
          CHANGES_BOT_GH_WEB: ${{ secrets.CHANGES_BOT_GH_WEB }}
        run: |
          jq -n \
            --arg gh_token "$CHANGES_BOT_GH_TOKEN" \
            --arg gh_api "$CHANGES_BOT_GH_API" \
            --arg gh_web "$CHANGES_BOT_GH_WEB" \
            '{github_token: $gh_token, github_api_endpoint: $gh_api, github_web_url: $gh_web, "repos": [{"name": "ONLYOFFICE/build_tools"}]}' > config.json
      - name: Build and test with Rake
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake
      - name: Check `simplecov` line coverage
        run: cat coverage/.last_run.json | jq '.result.line' | grep -q '100'
      - name: Check `simplecov` branch coverage
        run: cat coverage/.last_run.json | jq '.result.branch' | grep -q '100'
      - name: Check source files using `rubocop`
        run: bundle exec rubocop
      - name: Check that code 100% documented
        run: yardoc . | grep -q '100.00% documented'
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Default Dockerfile build
        run: docker build .
